name: build

on: [push, pull_request]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Upload dummy
        uses: actions/upload-artifact@v2
        with:
            name: dummy1
            path: dummy1.txt
  trigger-cd:
    runs-on: ubuntu-latest
    needs: test-build-deploy
    steps: 
      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          data: "{'deployment': 'finished', 'project': 'actions'}"

      